"""`horizon` CLI (doc 01 §7): serve | migrate | seed | reset [--factory --yes] | export-schema --check.

`serve` binds to loopback only (NFR-13); any other host is refused.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path

from horizon.config import DEFAULT_PORT, LOOPBACK, load_config

LOOPBACK_HOSTS = {"127.0.0.1", "localhost", "::1"}


def _serve(args: argparse.Namespace) -> int:
    if args.host not in LOOPBACK_HOSTS:
        print(f"horizon: refusing to bind to {args.host!r}. The backend is local-only (loopback).", file=sys.stderr)
        return 2
    import uvicorn

    if args.static:
        os.environ["HORIZON_STATIC_DIR"] = str(Path(args.static).resolve())
    if args.port:
        os.environ["HORIZON_PORT"] = str(args.port)
    cfg = load_config()
    reload_dirs = [str(Path(__file__).resolve().parent)] if args.reload else None
    uvicorn.run("horizon.main:create_app", factory=True, host=args.host, port=args.port or cfg.port, reload=args.reload,
                reload_dirs=reload_dirs, log_config=None, access_log=False)
    return 0


def _migrate(_args: argparse.Namespace) -> int:
    from horizon.db.migrate import upgrade_head

    cfg = load_config()
    upgrade_head(cfg.db_path)
    print(f"horizon: {cfg.db_path} is at head")
    return 0


def _with_runtime(action: str) -> int:
    from horizon.runtime import Runtime

    async def run() -> None:
        rt = Runtime(load_config())
        await rt.start()  # migrates, and imports the seed if the database is empty
        try:
            if action == "reset":
                await rt.reset_demo()
        finally:
            await rt.stop()

    asyncio.run(run())
    return 0


def _seed(_args: argparse.Namespace) -> int:
    rc = _with_runtime("seed")
    print("horizon: seed present")
    return rc


def _reset(args: argparse.Namespace) -> int:
    if args.factory:
        if not args.yes:
            print("horizon: factory reset deletes everything in data/ except models/. Re-run with --yes to confirm.",
                  file=sys.stderr)
            return 2
        from horizon.runtime import wipe_data_dir

        cfg = load_config()
        wipe_data_dir(cfg.data_dir)
        rc = _with_runtime("seed")
        print("horizon: factory reset done")
        return rc
    rc = _with_runtime("reset")
    print("horizon: demo data reset")
    return rc


def _export_schema(args: argparse.Namespace) -> int:
    from horizon.contract.validate import ContractSchema

    cfg = load_config()
    if not cfg.schema_path.is_file():
        print(f"horizon: {cfg.schema_path} is missing. Run `npm run export-schema` in frontend/.", file=sys.stderr)
        return 1
    schema = ContractSchema(cfg.schema_path)
    from horizon.api.routes import router

    needed = {"AppSettings", "World", "Character", "EmotionAsset", "ThemeSong", "MemoryItem", "KnowledgeSource",
              "KnowledgeChunk", "Session", "Message", "SessionEvent", "TurnTrace", "UsageRecord", "GenerationJob",
              "GlobalEvent", "HorizonErrorShape"}
    missing = sorted(d for d in needed if not schema.has(d))
    if missing:
        print(f"horizon: schema.json lacks {missing}. Run `npm run export-schema` in frontend/.", file=sys.stderr)
        return 1
    print(f"horizon: schema.json ok ({len(schema.defs)} definitions, {len(router.routes)} routes). "
          "It is generated by `npm run export-schema` in frontend/.")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="horizon", description="Horizon local backend (loopback only).")
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("serve", help="run the API server")
    s.add_argument("--host", default=LOOPBACK)
    s.add_argument("--port", type=int, default=None, help=f"default {DEFAULT_PORT} (HORIZON_PORT)")
    s.add_argument("--reload", action="store_true", help="restart on code changes (dev)")
    s.add_argument("--static", default=None, help="also serve a built frontend (npm run demo)")
    s.set_defaults(fn=_serve)
    sub.add_parser("migrate", help="apply database migrations").set_defaults(fn=_migrate)
    sub.add_parser("seed", help="import the seed if the database is empty").set_defaults(fn=_seed)
    r = sub.add_parser("reset", help="reset demo data (seed records only), or --factory to wipe data/")
    r.add_argument("--factory", action="store_true", help="delete everything in data/ except models/")
    r.add_argument("--yes", action="store_true", help="confirm --factory")
    r.set_defaults(fn=_reset)
    e = sub.add_parser("export-schema", help="check backend/horizon/contract/schema.json (generated by the frontend)")
    e.add_argument("--check", action="store_true")
    e.set_defaults(fn=_export_schema)
    args = p.parse_args(argv)
    return int(args.fn(args))


if __name__ == "__main__":
    raise SystemExit(main())
